name: Limit Concurrent Jobs

on:
  push:
    branches:
      - main

concurrency:
  group: my-workflow-${{ github.ref }}  # Group by branch
  cancel-in-progress: true

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Run a job
        run: echo "This job is running with concurrency control" 
 