name: Run Step Based on Secret

on:
  push:
    branches:
      - main

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Check if MY_SECRET is set
        if: ${{ secrets.MY_SECRET != '' }}
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}
        run: |
          echo "The secret MY_SECRET is set and not empty."
          echo "Its value is: $MY_SECRET"
